sonar.projectKey=ReutBenisho_code-quality-research
sonar.organization=reutbenisho
sonar.host.url=https://sonarcloud.io
sonar.token=69bdd4896cbf768edf05e78f3917bb581ad71a52
sonar.sources=dataset/
sonar.cfamily.build-wrapper-output.bypass=true
sonar.sourceEncoding=UTF-8